from datetime import date

from persona_lens.models import PersonaReport

_DAYS_ORDER = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
_DAYS_SHORT  = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
_BAR_WIDTH = 20

_SLOTS_ORDER = ["00-04", "04-08", "08-12", "12-16", "16-20", "20-24"]
_SLOTS_EMOJI = {
    "00-04": "🌙",
    "04-08": "🌅",
    "08-12": "☀️",
    "12-16": "⛅",
    "16-20": "🌇",
    "20-24": "🌃",
}


def _bar(count: int, max_count: int) -> str:
    filled = round(count / max_count * _BAR_WIDTH) if max_count else 0
    return "█" * filled + "░" * (_BAR_WIDTH - filled)


def _day_heatmap(posting_days: dict[str, int]) -> str:
    if not posting_days:
        return "No activity data available."
    max_count = max(posting_days.values())
    lines = []
    for day, short in zip(_DAYS_ORDER, _DAYS_SHORT):
        count = posting_days.get(day, 0)
        lines.append(f"{short} {_bar(count, max_count)} {count}")
    return "\n".join(lines)


def _hour_heatmap(posting_hours: dict[str, int]) -> str:
    if not posting_hours:
        return "No activity data available."
    max_count = max(posting_hours.values())
    lines = []
    for slot in _SLOTS_ORDER:
        count = posting_hours.get(slot, 0)
        emoji = _SLOTS_EMOJI[slot]
        lines.append(f"{emoji} {slot}  {_bar(count, max_count)} {count}")
    return "\n".join(lines)


def format_report(report: PersonaReport) -> str:
    traits    = "\n".join(f"- {t}" for t in report.personality_traits)
    interests = "\n".join(f"- {i}" for i in report.interests)
    expertise = "\n".join(f"- {e}" for e in report.expertise)
    values    = "\n".join(f"- {v}" for v in report.values)
    day_map   = _day_heatmap(report.posting_days)
    hour_map  = _hour_heatmap(report.posting_hours)

    return f"""# Persona Report: @{report.username}

**{report.display_name}** · {report.bio}

---

## 📋 Summary

{report.summary}

## 🧠 Personality Traits

{traits}

## 💬 Communication Style

{report.communication_style}

## ✍️ Writing Style

{report.writing_style}

## 🎯 Interests

{interests}

## 🏆 Areas of Expertise

{expertise}

## 💎 Core Values

{values}

## 📊 Posting Activity

**Day of week**

```
{day_map}
```

**Time of day (UTC)**

```
{hour_map}
```

### 🔍 Activity Insights

{report.activity_insights}

---
*Generated by persona-lens on {date.today()}*
"""
